# THIS IS AN EXAMPLE ON HOW YOU SHOULD CONFIGURE YOUR hugo.toml
# See this hugo.toml in action at https://github.com/1bl4z3r/hermit-V2/blob/staging/hugo.toml
# Example Site is Staging branch, acessible at https://github.com/1bl4z3r/hermit-V2/tree/staging
# To see what each config does, refer to https://1bl4z3r.github.io/hermit-V2/en/posts/explaining-configs/
# Open Issue or Pull Request at https://github.com/1bl4z3r/hermit-V2

baseURL = "johnson-cooper.github.io"
defaultContentLanguage = "en"
#defaultContentLanguageInSubdir = true
theme = "hermit-v2"
#enableRobotsTXT = true ## set to true to enable inbuilt robots.txt

#[languages]
#  [languages.en]
#    title = 'CHANGE ME'
#    [languages.en.params]
#      homeSubtitle = "CHANGE ME"
#    weight = 1
#  [languages.fr]
#    title = 'CHANGE ME(FR)'
#    [languages.fr.params]
#      homeSubtitle = "CHANGE ME"
#    weight = 2
#  [languages.it]
#    title = 'CHANGE ME(IT)'
#    [languages.it.params]
#      homeSubtitle = "CHANGE ME"
#    weight = 3
 
languageCode = "en-us"

 title = "Cooper Johnson"
 enableGitInfo = false

pygmentsCodefences  = true
pygmentsUseClasses  = true
#hasCJKLanguage = true

rssLimit = 10

copyright = "2025"
enableEmoji = true

#[services]
#  [services.disqus]
#    shortname = ''
#  [services.googleAnalytics]
#    id = ''

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]


#[params.author]
 # name = "Cooper Johnson"
  #about = "Professional App / Software Developer"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.
   category = "categories"

# Enable to get proper Mathjax support
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


[params]
   description = "Cooper Johnson - Online Portfolio"
  # images = [""]
  themeColor = "#494f5c"
  accentColor = "#018472"

 #homeSubtitle = "Cooper Johnson - Online Portfolio"
  footerCopyright = "2025"
  # footerHideThemeName = false
  # bgImg = ""
   gitUrl = "https://github.com/johnson-cooper"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = true
  readTimeSeparator = " , "
  # legacyLayout = false
  shareSocial = true
  # googleTagManager = "GTM-XXXXXXXX"
   tagSymbol = "#"
   categorySymbol = "‚ä≤"
  # pinned = "Pinned Posts"
  # pinnedSVGname = "pin"
  # listLayout = ["description","tags","categories","legacy"]
  # initialPublish = "Initally Posted on: "
  # human = ["single","posts"]
  # noIndex = false
  # denyRobots = "noindex, nofollow, noarchive"
  # allowRobots = "index, follow"
  # siteNoIndex = false
  # noIndexPages = ["404 Page not found"]
  # usesAnimation = true
  # mathjaxLib = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
  # mermaidLib = "https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.esm.min.mjs"
  [params.gallery]
    enable = true
    thumbnail = '300'

  [params.dateform]
    CopyrightDate = "2006"
    LongDate = "Jan 2, 2006"
    ShortDate = "Jan 2"
    NumDateShort = "2006-01-02"
    NumDateLong = "2006-01-02 15:04 -0700"
  
  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/johnson-cooper"

  [[params.socialLinks]]
    name = "attackishere"
    url = "https://attackishere.com"

  #[[params.socialLinks]]
   # name = "x"
    #url = "https://twitter.com/"



[menu]

  [[menu.main]]
    name = "Portfolio"
    url = "categories/"
    weight = 10

    [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 20

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 30

    [[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 40